name: Publish NPM Package

on:
  release:
    types: [created]

permissions:
  contents: read
  id-token: write

jobs:
  verify:
    uses: ./.github/workflows/base-verify.yml

  publish:
    name: Publish
    needs: verify
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: package-lock.json
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm ci
      - name: Build package
        run: npm run build
      - name: Publish to npm
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
      - name: Verify published package
        run: |
          npm pack --dry-run
          npm view ${{ env.npm_package_name }}@${{ env.npm_package_version }}
